### PR TITLE
Handle Linux systems that use /lib64 instead of /lib

### PR DESCRIPTION
**Pull request by Tabby**
Use `CMAKE_INSTALL_LIBDIR` variable to set the correct lib folder to use for installing libraries so that CMake looks in the right place for the dependencies when linking

This shouldn't affect builds on other systems, both Linux and otherwise, but it fixes it for systems that prefer /lib64

### CODE REVIEW

**Review by royshil — APPROVED** [review]
looks great!

**Comment by royshil** [comment]
@Tabby do you mind fixing the cmake so it passes linting?

**Comment by Tabby** [comment]
Not at all! Also yes of course there's a CMake linter, my bad. Must get that set up locally 😅

**Comment by Tabby** [comment]
Ugh, I think this approach is wrong, as it causes the Ubuntu build to fail with the error I was getting on Gentoo before this change :/

**Comment by royshil** [comment]
going to close now for staleness
lmk if more work is needed on this

**Pull request closed without merging**
