### PR TITLE
fix: fix obs crash when use 7.1 channel

### LINKED ISSUE #73: Crash upon adding audio filter with 7.1 channel
Hi! Plugin looks like a great concept, however,as soon as I add it as an audio filter to my capture device obs  freezes and after a few seconds of waiting it crashes with no errors or anything.

I can only add it as an audio filter when I mute the audio first.

I tried to build the latest code. But keep got LNK 2019 error complaing about missing __ms_vsnprintf when building obs. I managed to bypass this by bumping obs to 30.0.2, which is my current version. It can be built with or without cuda. But it just keeps crashing.

Let me know if need to gather more info.

Here is all the crash logs i have now.

[Crash 2024-03-10 03-29-32.txt](https://github.com/occ-ai/obs-localvocal/files/14548110/Crash.2024-03-10.03-29-32.txt)
[Crash 2024-03-10 03-54-32.txt](https://github.com/occ-ai/obs-localvocal/files/14548111/Crash.2024-03-10.03-54-32.txt)
[Crash 2024-03-10 04-03-29.txt](https://github.com/occ-ai/obs-localvocal/files/14548112/Crash.2024-03-10.04-03-29.txt)

Most time it just crash without crash log. So I add obs running log as a supplement.

[2024-03-10 06-25-51.txt](https://github.com/occ-ai/obs-localvocal/files/14548133/2024-03-10.06-25-51.txt)

As far as I'm aware, the last log before crash is always like this and end with `starting whisper thread`
```
07:19:04.368: warning: Could not update timestamps for skipped samples.
07:19:54.985: [obs-localvocal] transcription_filter_defaults
07:19:54.985: [obs-localvocal] transcription filter create
07:19:54.985: [obs-localvocal] Checking if model models/ggml-tiny.en.bin exists in data...
07:19:54.986: [obs-localvocal] Model found in data: ../../data/obs-plugins/obs-localvocal/models/ggml-tiny.en.bin
07:19:54.986: [obs-localvocal] Loading whisper model from ../../data/obs-plugins/obs-localvocal/models/ggml-tiny.en.bin
07:19:55.324: [obs-localvocal] Whisper model loaded: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | METAL = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | CUDA = 1 | COREML = 0 | OPENVINO = 0 | 
07:19:55.328: User added filter 'LocalVocal Transcription' (transcription_filter_audio_filter) to source '媒体源'
07:19:55.328: [obs-localvocal] transcription_filter_defaults
07:19:55.329: [obs-localvocal] starting whisper thread
```

### PR DESCRIPTION
**Pull request by A0nameless0man**
Fix #73

### CODE REVIEW

**Comment by A0nameless0man** [comment]
https://github.com/occ-ai/obs-localvocal/blob/240f7dd817efae0cbce99bfcf98d4aeca8742b2e/src/transcription-filter.cpp#L104-L107

**Comment by royshil** [comment]
@A0nameless0man does this solve the crash for you? i also wonder why no one else ran into the problem

**Comment by A0nameless0man** [comment]
I'm reverting other changes I made to verify that this is the only patch needed for my problem.

I assume that stream or record in 7.1 is a niche activity.

**Comment by A0nameless0man** [comment]
Confirmed, this patch alone can fix my problem.

**Comment by royshil** [comment]
Cool. In general this checks out
However there are build problems that are unrelated to your patch

So I think I'll have to bring up a PR fixing this and other things.

**Comment by royshil** [comment]
@A0nameless0man plz see #75

**Pull request closed without merging**
